### ISSUE TITLE
Talk: Using Swift enums with collection views and table views

### ISSUE THREAD

**Issue by arielelkin** [swift-berlin/swift-berlin.github.io#16]
A good way to let the Swift compiler help you build a rock-solid `UICollectionView` or `UITableView` is to manage their layout structure through an enum. This talk will show you a simple and safe way to implement this in your Swift apps.

**Comment by JensRavens** [comment]
Great, that's exactly what's still missing for this meetup. Great to have you on board!

Could you please fill out this form for the website?

``` yaml
-
    name: Jens Ravens
    image: jensravens
    title: Async Transformations with Interstellar
    about: 'Jens is an iOS and OS X Developer, writing ObjC since 2006. Currently working at <a href="http://nerdgeschoss.de" target="new">nerdgeschoss</a> helping clients to create awesome apps.'
    abstract: Who's afraid of the monad? Let's have a look at results, signals and why concurrency doesn't have to be evil.
    links:
      -
        url: http://jensravens.com
        name: jensravens.com
      -
        url: https://twitter.com/jensravens
        name: '@JensRavens'
```

**Comment by arielelkin** [comment]
```
-
    name: Ariel Elkin
    image: https://en.gravatar.com/userimage/20806541/0aceab9f0ce41d2cd491b6bfe204621c.jpg?size=400
    title: Using Swift enums with collection views and table views
    about: 'Ariel is an iOS developer, with big interest in audio and blockchains. He contributes to open source libraries and puts his dishes in the dishwasher. Currently working at at <a href="https://www.project-a.com/" target="new">Project A</a>.'
    abstract: A good way to let the Swift compiler help you build a rock-solid <pre>UICollectionView</pre> or <pre>UITableView</pre> is to manage their layout structure through an enum. This talk will show you a simple and safe way to implement this in your Swift apps.
    links:
      -
        url: http://arielelkin.github.io/
        name: Ariel's website
      -
        url: https://twitter.com/arivocals
        name: '@AriVocals'
```
