### ISSUE TITLE
Dependency Injection in Swift

### ISSUE THREAD

**Issue by ilyapuchka** [swift-berlin/swift-berlin.github.io#22]
``` yaml
name: Ilya Puchka
company: HelloFresh
title: Dependency Injection in Swift
abstract: Dependency Injection is a simple but powerful technique that helps to write loosely coupled code. Let's talk about what DI is and what it is not and specifically how we can do it in Swift.
links:
  -
    url: https://twitter.com/ilyapuchka
    name: '@ilyapuchka'
  -
    url: http://ilya.puchka.me
    name 'Personal blog'
```
