### ISSUE TITLE
VIPER in iOS app #talk

### ISSUE THREAD

**Issue by kandelvijaya** [swift-berlin/swift-berlin.github.io#23]
``` yaml
name: Vijaya Prakash Kandel (BJ)
company: Zalando SE
title: VIPER Architecture in iOS talk
abstract: Inspired by Uncle Bobs Clean Code, VIPER. In this talk I will demo a working app with how the internals are wired up. We will go through the interesting principles and motivations behind why we choose to use VIPER too. And be ready to some code samples.
links:
  -
    url: http://www.kandelvijaya.com
    name: '@kandelvijaya'

```
