### ISSUE TITLE
Xcode UI Testing

### ISSUE THREAD

**Issue by MattesGroeger** [swift-berlin/swift-berlin.github.io#24]
``` yaml
name: Mattes Groeger
company: IDAGIO GmbH
title: Xcode UI Testing
abstract: This talk will shed some light on the new Xcode UI Testing with a real world app (not the typical example app). I want to show you why it's such a powerful tool und why you should make use of it. This _won't_ be a basic setup live-coding talk. It's aimed at experienced iOS developers who are curious on how to further automate their workflow and improve their app quality.
links:
  -
    url: https://twitter.com/MattesGroeger
    name: '@MattesGroeger'
  -
    url: https://www.idagio.com
    name: 'Idagio – The new way to enjoy classical music'
```
