### ISSUE TITLE
Utilizing AVFoundation at Dubsmash

### ISSUE THREAD

**Issue by gapl** [swift-berlin/swift-berlin.github.io#25]
``` yaml
name: Gasper Kolenc
company: Dubsmash
title: Utilizing AVFoundation at Dubsmash
abstract: I will present the Dubsmash video creation flow based on where we use AVFoundation to its fullest extent. It has been very much a love / hate relationship with AVFoundation so I will also present some pitfalls we faced and how to overcome them.
links:
  -
    url: https://www.dubsmash.com/
    name: 'Website'
```

I would like to do a full featured talk at the upcoming meetup at Dubsmash HQ.
