### ISSUE TITLE
REST API's in Swift

### ISSUE THREAD

**Issue by endocrimes** [swift-berlin/swift-berlin.github.io#26]
``` yaml
name: Daniel Tomlinson
company: Ride
title: REST API's in Swift
abstract: An introduction to building REST API's in Swift, starting with an intro to the key components and tools before then diving in to building a simple todo list API.
links: 
  -
    url: https://twitter.com/dantoml
    name: '@dantoml'
  -
    url: https://dantoml.com
    name 'Website'
```

I don't live in Berlin, but visit a lot, and will be in town next week if you'd be interested in the talk?
