### ISSUE TITLE
Developing User Interfaces

### ISSUE THREAD

**Issue by blinker13** [swift-berlin/swift-berlin.github.io#27]
``` yaml
name: Felix Gabel
company: SoundCloud
title: Developing User Interfaces
abstract: This talk is about concepts for implementing scalable user interfaces and what a potential solution for developing user interfaces with Swift might look like in the future.
links:
  -
    url: https://twitter.com/blinker13
    name: '@blinker13'
```
