### ISSUE TITLE
UI Tests with Earl Grey

### ISSUE THREAD

**Issue by shyambhat** [swift-berlin/swift-berlin.github.io#28]
``` yaml
name: Shyam Bhat
company: ImmobilienScout24
title: UI Testing with Earl Grey
abstract: An introduction to Earl Grey - Google's powerful UI Automation Framework for native iOS Apps and a demo of its usage in the ImmobilienScout App. 
links: https://github.com/google/EarlGrey
  -
    url: https://twitter.com/bhatthead
    name: '@bhatthead'
```
