### ISSUE TITLE
[Lightning Talk] SwiftyRuby

### ISSUE THREAD

**Issue by marciok** [swift-berlin/swift-berlin.github.io#29]
``` yaml
name: Marcio Klepacz
company: 
title: SwiftyRuby
abstract: I'd like to demonstrate an experiment where I call ruby code from Swift, and discuss its possible usefulness --if there is any :P
links:
  -
    url: https://twitter.com/marciok
    name: '@marciok'
  -
    url: http://github.com/marciok
    name: 'Github'
```
