### ISSUE TITLE
Talk: SwiftyBeaver (Meetup #21)

### ISSUE THREAD

**Issue by ckroter** [swift-berlin/swift-berlin.github.io#30]
For Meetup #21

``` yaml
name: Sebastian Kreutzberger
company: 
title: My awesome talk
abstract: This is an abstract about the most awesome talk you've ever heard about.
links:
  -
    url: https://twitter.com/swift-berlin
    name: '@swift-berlin'
  -
    url: https://google.com
    name 'Website'
```
