### ISSUE TITLE
Sound manipulation with AVAudioEngine

### ISSUE THREAD

**Issue by gapl** [swift-berlin/swift-berlin.github.io#31]
``` yaml
name: Gasper Kolenc
company: Dubsmash
title: Sound manipulation with AVAudioEngine
abstract: I will present how we achieve sound manipulation at Dubsmash to make videos more engaging. I will talk how one can achieve both live audio manipulation as well as later exporting the manipulated audio files themselves.
links:
  -
    url: https://www.dubsmash.com/
    name 'Website'
```
