### ISSUE TITLE
Recursive Enums, Value Types in Swift & Performance Analysis

### ISSUE THREAD

**Issue by Bersaelor** [swift-berlin/swift-berlin.github.io#32]
``` yaml
name: Konrad Feiler
company: Viacom
title: Recursive Enums, Value Types in Swift & Performance Analysis
abstract: One feature in Swift that is often overlooked are indirect enum cases. With those we can create tree based data structures that are benefiting from Swifts efficient value types. In my talk I will explain this, using the an example called KD-Tree a k-dimensional binary space partitioning tree that is used for nearest neighbour searches among other things. Furthermore I will present performance results that present the advantages of of value types in general.
bio: Working as a freelance dev since iOS 3.2, I have recently taken over the job of lead developer for Viacom in Berlin. At Viacom we work on international video on demand apps for brands like ComedyCentral, Nickelodeon or MTV.
audience: both Swift beginners who want to learn more about value types and intermediate developers who are interested in the advanced features of enums. 
links:
  -
    url: https://twitter.com/bersaelor
    name: '@bersaelor'
  -
    url: https://github.com/Bersaelor/KDTree
    name: 'Example project'
  -
    url: http://www.viacom.de
    name: 'Website'
```

![knearest](https://cloud.githubusercontent.com/assets/4517582/17250602/5181f40a-55a5-11e6-94a5-84317c8d747a.png)
