### ISSUE TITLE
Running and deploying Swift server applications with Docker

### ISSUE THREAD

**Issue by choefele** [swift-berlin/swift-berlin.github.io#33]
``` yaml
name: Claus Höfele
company: HERE
title: Running and deploying Swift server applications with Docker
abstract: An introduction to Docker with examples on how to containerize a Swift server application.
links:
  -
    url: https://twitter.com/claushoefele
    name: '@claushoefele'
```
