### ISSUE TITLE
Snapshot testing with FBSnapshotTestCase

### ISSUE THREAD

**Issue by Geek-1001** [swift-berlin/swift-berlin.github.io#34]
``` yaml
name: Ahmed Sulaiman
company:  Flawless App
title: Snapshot testing with FBSnapshotTestCase
abstract: Brief introduction to FBSnapshotTestCase. How to use it properly. And why you should do it
audience: Swift Beginners
links:
  -
    url: https://twitter.com/ahmed_sulajman
    name: '@ahmed_sulajman'
  -
    url: https://flawlessapp.io
    name 'Website'
```
