### ISSUE TITLE
Space Galaxy Rogue (Lightning Talk)

### ISSUE THREAD

**Issue by vironrd** [swift-berlin/swift-berlin.github.io#38]
```yaml
name: Ronny Deicke
company: 
title: "Space Galaxy Rogue" - iOS Game
abstract: SGRogue is an iOS Game I started developing one year ago and it's finally in the Beta Test phase. I want to present the latest build and also want to share some things which helped me developing the game. 
links:
  -
    url: https://www.facebook.com/SGRogue/
    name: 'Space Galaxy Rogue Facebook page'
  -
    url: https://www.youtube.com/watch?v=6JbZGA5SvVM
    name '"Space Galaxy Rogue" Teaser Trailer'
```
