### ISSUE TITLE
From Cocoapods to manual dependency management.

### ISSUE THREAD

**Issue by DmitryBespalov** [swift-berlin/swift-berlin.github.io#39]
```yaml
name: Dmitry Bespalov
company: Zalando SE
title: How moving to manual dependency management saved us app startup and build time.
abstract: Cocoapods is a de-facto standard in iOS dependency management. Nevertheless, with complex project structure it becomes hard to maintain. I'll tell you a story of transitioning our project from Cocoapods to manual dependency management, which improved our project structure, build time and app startup time.
links:
  -
    url: https://twitter.com/dnbespalov
    name: '@dnbespalov'
```
