### ISSUE TITLE
CoreData made easy

### ISSUE THREAD

**Issue by arashkashi** [swift-berlin/swift-berlin.github.io#40]
```yaml
name: Arash Kashi
company: Feingold GmbH
title: How I came with peace with CoreData.
abstract: I have seen applications adapting big CoreData dependency using third party libraries. Other than the pain of adding a new dependency, the new notations and understanding of the third party libraries introduces some disadvantages. CoreData appears to be tad challenging to setup and take advantaged of but when well understood it is a very powerful data storage tool. In the past 6 months I created a small wrapper solution with about 100 lines of code, using swift and some protocols which makes the use of CoreData much easier. Let's see what is happening there and  if it appears convincing to other developers. Feel free to check out the repository in the link below. 
  -
    url: https://github.com/arashkashi/Learncoredata/
    name 'Learn Core Data'
  -
```
