### ISSUE TITLE
Protobuf: Is it better than JSON?

### ISSUE THREAD

**Issue by justMaku** [swift-berlin/swift-berlin.github.io#41]
```yaml
name: Michał Kałużny
company: Clue
title: Protobuf: Is it better than JSON?
abstract: Since the dawn of time, developers around the world have been asking the same question: "So... How do I parse JSON in Swift?". But maybe, just maybe, there's an alternative to all this madness? Let's find out.
links:
  -
    url: https://twitter.com/justMaku
    name: '@justMaku'
```
