### ISSUE TITLE
Deep Learning on iOS

### ISSUE THREAD

**Issue by jackflips** [swift-berlin/swift-berlin.github.io#42]
```yaml
name: Jack Rogers
company: Clarifai
title: Deep Learning on iOS
abstract: This talk examines the current state of deep learning on mobile, diving deep on Tensorflow XLA and the Clarifai SDK, which aims to make it really easy for devs to train and use models on device.
links:
  -
    url: https://twitter.com/jackflips
  -
    url: https://github.com/jackflips
```
