### ISSUE TITLE
Unidirectional Dataflow with ReSwift

### ISSUE THREAD

**Issue by ekurutepe** [swift-berlin/swift-berlin.github.io#43]
```yaml
name: Engin Kurutepe
company: Keepsafe
title: Unidirectional Dataflow with ReSwift
abstract: ReSwift is a Redux-like implementation of the unidirectional data flow architecture in Swift. It helps you to isolate state inside your app and manage state transitions and propagation of state to various components in your app in a well-defined, predictable and testable fashion.
links:
  -
    url: https://twitter.com/ekurutepe
    name: '@ekurutepe'
  -
    url: https://kurutepe.com
    name 'Website'
```
